name: Generate Pydantic Models

on:
  push:
    branches:
      - main
    paths:
      - 'catalog-rest-service/src/main/resources/json/**'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit Models
        run: |
          set -ex
          make generate
          git config --global user.name 'open-metadata'
          git config --global user.email 'open-metadata@users.noreply.github.com'
          git add -A
          git commit -m "Automated Pydantic Models generation"
          git push
